[[versions]]
version = "0.2.1"
date = "2025-12-03"
summary = "各要素の余白などデザインの微調整"
added = []
changed = []
fixed = []

[[versions]]
version = "0.2.0"
date = "2025-12-03"
summary = "FooterでのSNSリンクのバグ修正"
added = []
changed = []
fixed = []

[[versions]]
version = "0.1.1"
date = "2025-12-03"
summary = "総研大アドベントカレンダー2025の記事追加"
added = []
changed = []
fixed = []

[[versions]]
version = "0.1.0"
date = "2025-12-02" # 最新のリリース日以降の日付
summary = "情報の整備とコンテンツの移植"
added =  []
changed = []
fixed = []

[[versions]]
version = "0.0.1"
date = "2025-11-29"
summary = "Astroプロジェクトの初期セットアップ"
added = []
changed = []
fixed = []
